version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate go files from protobuff"
    cmds:
      - protoc -I proto proto/pet/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
